### ISSUE TITLE
Get summary in string format

### ISSUE THREAD

**Issue by dvolgyes** [blue-season/pywarm#14]
Hi,

It would be nice to get the summary in string format too, e.g. if someone uses a logger.
I would recommend to move the content of the summary function into a summary_str function,
and summary would be just a short wrapper like this:
```
def summary(model):
      for line in summary_str(model):
           print(line)
```
Or alternatively an optional flag, e.g. output='print' | 'str' | file_like_object. (default: 'print').

**Comment by blue-season** [comment]
Addressed in b699cd59b2505502150f714871ec60fde093215c
