### ISSUE TITLE
'MyWarmModule' object has no attribute 'training'

### ISSUE THREAD

**Issue by steven-lang** [blue-season/pywarm#3]
Your quick start example does not work. Running the following:

```python
import torch
from torch import nn
import warm
import warm.functional as W

# Warm
class MyWarmModule(nn.Module):
    def __init__(self):
        warm.engine.prepare_model_(self, [1, 1, 28, 28])

    def forward(self, x):
        z = W.conv(x, 5, 3)
        return z


if __name__ == "__main__":
    x = torch.randn(5, 1, 28, 28)
    model = MyWarmModule()
    model(x)
```

Results in 

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model = MyWarmModule()
  File "test.py", line 9, in __init__
    warm.engine.prepare_model_(self, [1, 1, 28, 28])
  File "/home/tak/.local/lib/python3.7/site-packages/warm/engine.py", line 58, in prepare_model_
    is_training = model.training
  File "/home/tak/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'MyWarmModule' object has no attribute 'training'
```

### Details
- PyTorch version 1.1.0
- PyWarm version 0.1.1

**Comment by blue-season** [comment]
Thanks for pointing it out.
The code in quick start is an excerpt of bare minimum component, not meant to be working code.  You still need `super().__init__()` just like all inherited modules:

```Python
# Warm
class MyWarmModule(nn.Module):
    def __init__(self):
        super().__init__()
        warm.engine.prepare_model_(self, [1, 1, 28, 28])
```
I will update the documents accordingly.

**Comment by steven-lang** [comment]
Thanks, the quick start left the impression that it wasn't necessary.

Additionally, you might want to reconsider using `...` literally in the examples since `...` is the [python ellipsis object](https://docs.python.org/3/library/constants.html#Ellipsis).

**Comment by blue-season** [comment]
> Additionally, you might want to reconsider using `...` literally in the examples since `...` is the [python ellipsis object](https://docs.python.org/3/library/constants.html#Ellipsis).

Good point. I will update the docs shortly. Thanks.
